image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - rogalmic.bash-debug
    - mads-hartmann.bash-ide-vscode
    - bmalehorn.vscode-fish
    - redhat.vscode-yaml
    - redhat.vscode-xml
    - ms-python.python
    - ms-vscode.Go
    - quicktype.quicktype
    - naumovs.color-highlight
    - lihui.vs-color-picker
    - vscode-icons-team.vscode-icons
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - donjayamanne.githistory
    - humao.rest-client
    - jebbs.plantuml
    - ionutvmi.path-autocomplete
    - mechatroner.rainbow-csv
    - ryu1kn.partial-diff
    - GitHub.vscode-pull-request-github
    - emilast.LogFileHighlighter
    - IBM.output-colorizer
    - zxh404.vscode-proto3
    - chrmarti.regex
    - shardulm94.trailing-spaces
    - wiggin77.codedox
    - DavidAnson.vscode-markdownlint
    - oderwat.indent-rainbow
    - ms-azuretools.vscode-docker
    - streetsidesoftware.code-spell-checker
    - ms-vscode.cpptools
    - ms-dotnettools.csharp
    - redhat.java
    - MS-vsliveshare.vsliveshare
    - MS-vsliveshare.vsliveshare-audio
    - MS-vsliveshare.vsliveshare-pack
    - lostintangent.vsls-whiteboard



# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
